/****************
 * This code was automatically generated by lwm2m_codegen.
 ****************/
package org.eclipse.leshan.client.demo;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Random;
import java.util.List;
import java.util.Arrays;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.Scanner;

import org.eclipse.leshan.client.servers.ServerIdentity;
import org.eclipse.leshan.client.resource.BaseInstanceEnabler;
import org.eclipse.leshan.core.model.ResourceModel.Type;
import org.eclipse.leshan.core.model.ObjectModel;
import org.eclipse.leshan.core.node.LwM2mResource;
import org.eclipse.leshan.core.request.argument.Arguments;
import org.eclipse.leshan.core.response.ExecuteResponse;
import org.eclipse.leshan.core.response.ReadResponse;
import org.eclipse.leshan.core.response.WriteResponse;
import org.eclipse.leshan.core.util.NamedThreadFactory;


import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JFrame;
import javax.swing.JComboBox;
import javax.swing.WindowConstants;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Container;
import java.awt.GridLayout;
import java.awt.EventQueue;

public class Battery extends BaseInstanceEnabler {
    static final int OBJECT_ID_BATTERY = 33005;
    static final int OBJECT_ID = 33005;
    // Static values for resource items
    private static final int RES_BUFFERED_ENERGY = 30012;
    private static final List<Integer> supportedResources =
     Arrays.asList(
             RES_BUFFERED_ENERGY
           );
    // Variables storing current values.

    private long vBufferedEnergy = 0;
   private JLabel glBufferedEnergy;
   private JLabel gvBufferedEnergy;
   private JTextField tfBufferedEnergy;
   private JFrame guiFrame;

  public Battery() {
      //  Automatically generated GUI code.
    guiFrame = new JFrame();
    guiFrame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    guiFrame.setTitle("Battery");

  // Buffered energy
    glBufferedEnergy = new JLabel();
    glBufferedEnergy.setText("Buffered energy");
    gvBufferedEnergy = new JLabel();
    gvBufferedEnergy.setText("");
    tfBufferedEnergy = new JTextField();
    tfBufferedEnergy.addActionListener(new java.awt.event.ActionListener() {
       public void actionPerformed(java.awt.event.ActionEvent evt) {
           String sValue = (String)tfBufferedEnergy.getText();
           setBufferedEnergy(Long.valueOf(sValue));
       }
     });

  // Create layout of labels, inputs and values.
   GridLayout layout = new GridLayout(0,3,10,10);
   guiFrame.getContentPane().setLayout(layout);
   Container guiPane = guiFrame.getContentPane();
   guiPane.add(glBufferedEnergy);
   guiPane.add(tfBufferedEnergy);
    guiPane.add(gvBufferedEnergy);
  guiFrame.pack();
  // Code to make the frame visible.
  java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
         guiFrame.setVisible(true);
      }
    });
  }

  @Override
  public synchronized ReadResponse read(ServerIdentity identity, int resourceId) {
    switch (resourceId) {
    case RES_BUFFERED_ENERGY:
         return ReadResponse.success(resourceId, vBufferedEnergy);
    default:
      return super.read(identity, resourceId);
    }
  }

  @Override
  public WriteResponse write(ServerIdentity identity, boolean replace, int resourceId, LwM2mResource value) {
    switch (resourceId) {
    case RES_BUFFERED_ENERGY:
        // vBufferedEnergy = (Long) value.getValue();
        // fireResourceChange(resourceId);
        setBufferedEnergy((Long) value.getValue());
        return WriteResponse.success();
    default:
      return super.write(identity, replace, resourceId,value);
    }
  }

  @Override
  public synchronized ExecuteResponse execute(ServerIdentity identity, int resourceId, Arguments arguments) {
    switch (resourceId) {
    default:
      return super.execute(identity, resourceId,arguments);
    }
  }

  @Override
  public List<Integer> getAvailableResourceIds(ObjectModel model) {
     return supportedResources;
  }

  private synchronized void setBufferedEnergy(long value) {
    if (vBufferedEnergy != value) {
       vBufferedEnergy = value;
 gvBufferedEnergy.setText(Long.toString(vBufferedEnergy));
       fireResourceChange(RES_BUFFERED_ENERGY);
    }
  }

}
