name: "Semantic Version Check"
description: "Check API against Semantic versioning rules"

inputs:
  build_status_filename:  
    description: 'Path to build status properties file'
    required: true

runs:
  using: "composite"
  steps:

  - name: Check API break
    id: main
    shell: bash
    run: mvn -B revapi:check

    # Store Step status in Build Status Properties file
  - name: Store Step Status
    if: always()
    # unstrusted action use commit ID instead of version 
    uses: GuillaumeFalourd/write-java-properties-file@c6762204aa02d62718ed285bca4cbcc400c65a10 #v1
    with:
      file_path: ${{inputs.build_status_filename}}
      property: ${{github.action}}
      value: ${{steps.main.outcome}}