/****************
 * This code was automatically generated by lwm2m_codegen.
 ****************/
package org.eclipse.leshan.client.demo;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Random;
import java.util.List;
import java.util.Arrays;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.Scanner;

import org.eclipse.leshan.client.servers.ServerIdentity;
import org.eclipse.leshan.client.resource.BaseInstanceEnabler;
import org.eclipse.leshan.core.model.ResourceModel.Type;
import org.eclipse.leshan.core.model.ObjectModel;
import org.eclipse.leshan.core.node.LwM2mResource;
import org.eclipse.leshan.core.request.argument.Arguments;
import org.eclipse.leshan.core.response.ExecuteResponse;
import org.eclipse.leshan.core.response.ReadResponse;
import org.eclipse.leshan.core.response.WriteResponse;
import org.eclipse.leshan.core.util.NamedThreadFactory;


import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JFrame;
import javax.swing.JComboBox;
import javax.swing.WindowConstants;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Container;
import java.awt.GridLayout;
import java.awt.EventQueue;

public class Bid extends BaseInstanceEnabler {
    static final int OBJECT_ID_BID = 33007;
    static final int OBJECT_ID = 33007;
    // Static values for resource items
    private static final int RES_ROOMCONTROL_NAME = 30016;
    private static final int RES_BID_STATE = 30017;
    private static final int RES_REQUESTED_ENERGY_AMOUNT = 30018;
    private static final int RES_REQUESTED_PRICE_PER_ENERGY_UNIT = 30019;
    private static final List<Integer> supportedResources =
     Arrays.asList(
             RES_ROOMCONTROL_NAME
           , RES_BID_STATE
           , RES_REQUESTED_ENERGY_AMOUNT
           , RES_REQUESTED_PRICE_PER_ENERGY_UNIT
           );
    // Variables storing current values.

    private String vRoomcontrolName = "";
   private JLabel glRoomcontrolName;
   private JLabel gvRoomcontrolName;
   private JTextField tfRoomcontrolName;

  // Init, Success,Failure,Exception
    private String vBidState = "";
   private JLabel glBidState;
   private JLabel gvBidState;
   private JComboBox cbBidState;
   private String[] cbvBidState = { "Init", "Success", "Failure", "Exception" };

    private long vRequestedEnergyAmount = 0;
   private JLabel glRequestedEnergyAmount;
   private JLabel gvRequestedEnergyAmount;
   private JTextField tfRequestedEnergyAmount;

    private long vRequestedPricePerEnergyUnit = 0;
   private JLabel glRequestedPricePerEnergyUnit;
   private JLabel gvRequestedPricePerEnergyUnit;
   private JTextField tfRequestedPricePerEnergyUnit;
   private JFrame guiFrame;

  public Bid() {
      //  Automatically generated GUI code.
    guiFrame = new JFrame();
    guiFrame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    guiFrame.setTitle("Bid");

  // RoomControl Name
    glRoomcontrolName = new JLabel();
    glRoomcontrolName.setText("RoomControl Name");
    gvRoomcontrolName = new JLabel();
    gvRoomcontrolName.setText("");
    tfRoomcontrolName = new JTextField();
    tfRoomcontrolName.addActionListener(new java.awt.event.ActionListener() {
       public void actionPerformed(java.awt.event.ActionEvent evt) {
           String sValue = (String)tfRoomcontrolName.getText();
           setRoomcontrolName(String.valueOf(sValue));
       }
     });

  // Bid state
    glBidState = new JLabel();
    glBidState.setText("Bid state");
    gvBidState = new JLabel();
    gvBidState.setText("");
    cbBidState = new JComboBox(cbvBidState);
    cbBidState.addActionListener(new java.awt.event.ActionListener() {
       public void actionPerformed(java.awt.event.ActionEvent evt) {
           String sValue = (String)cbBidState.getSelectedItem();
           setBidState(String.valueOf(sValue));
       }
     });

  // Requested Energy Amount
    glRequestedEnergyAmount = new JLabel();
    glRequestedEnergyAmount.setText("Requested Energy Amount");
    gvRequestedEnergyAmount = new JLabel();
    gvRequestedEnergyAmount.setText("");
    tfRequestedEnergyAmount = new JTextField();
    tfRequestedEnergyAmount.addActionListener(new java.awt.event.ActionListener() {
       public void actionPerformed(java.awt.event.ActionEvent evt) {
           String sValue = (String)tfRequestedEnergyAmount.getText();
           setRequestedEnergyAmount(Long.valueOf(sValue));
       }
     });

  // Requested price per energy unit
    glRequestedPricePerEnergyUnit = new JLabel();
    glRequestedPricePerEnergyUnit.setText("Requested price per energy unit");
    gvRequestedPricePerEnergyUnit = new JLabel();
    gvRequestedPricePerEnergyUnit.setText("");
    tfRequestedPricePerEnergyUnit = new JTextField();
    tfRequestedPricePerEnergyUnit.addActionListener(new java.awt.event.ActionListener() {
       public void actionPerformed(java.awt.event.ActionEvent evt) {
           String sValue = (String)tfRequestedPricePerEnergyUnit.getText();
           setRequestedPricePerEnergyUnit(Long.valueOf(sValue));
       }
     });

  // Create layout of labels, inputs and values.
   GridLayout layout = new GridLayout(0,3,10,10);
   guiFrame.getContentPane().setLayout(layout);
   Container guiPane = guiFrame.getContentPane();
   guiPane.add(glRoomcontrolName);
   guiPane.add(tfRoomcontrolName);
    guiPane.add(gvRoomcontrolName);
   guiPane.add(glBidState);
   guiPane.add(cbBidState);
    guiPane.add(gvBidState);
   guiPane.add(glRequestedEnergyAmount);
   guiPane.add(tfRequestedEnergyAmount);
    guiPane.add(gvRequestedEnergyAmount);
   guiPane.add(glRequestedPricePerEnergyUnit);
   guiPane.add(tfRequestedPricePerEnergyUnit);
    guiPane.add(gvRequestedPricePerEnergyUnit);
  guiFrame.pack();
  // Code to make the frame visible.
  java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
         guiFrame.setVisible(true);
      }
    });
  }

  @Override
  public synchronized ReadResponse read(ServerIdentity identity, int resourceId) {
    switch (resourceId) {
    case RES_ROOMCONTROL_NAME:
         return ReadResponse.success(resourceId, vRoomcontrolName);
    case RES_BID_STATE:
         return ReadResponse.success(resourceId, vBidState);
    case RES_REQUESTED_ENERGY_AMOUNT:
         return ReadResponse.success(resourceId, vRequestedEnergyAmount);
    case RES_REQUESTED_PRICE_PER_ENERGY_UNIT:
         return ReadResponse.success(resourceId, vRequestedPricePerEnergyUnit);
    default:
      return super.read(identity, resourceId);
    }
  }

  @Override
  public WriteResponse write(ServerIdentity identity, boolean replace, int resourceId, LwM2mResource value) {
    switch (resourceId) {
    case RES_ROOMCONTROL_NAME:
        // vRoomcontrolName = (String) value.getValue();
        // fireResourceChange(resourceId);
        setRoomcontrolName((String) value.getValue());
        return WriteResponse.success();
    case RES_BID_STATE:
        // vBidState = (String) value.getValue();
        // fireResourceChange(resourceId);
        setBidState((String) value.getValue());
        return WriteResponse.success();
    case RES_REQUESTED_ENERGY_AMOUNT:
        // vRequestedEnergyAmount = (Long) value.getValue();
        // fireResourceChange(resourceId);
        setRequestedEnergyAmount((Long) value.getValue());
        return WriteResponse.success();
    default:
      return super.write(identity, replace, resourceId,value);
    }
  }

  @Override
  public synchronized ExecuteResponse execute(ServerIdentity identity, int resourceId, Arguments arguments) {
    switch (resourceId) {
    default:
      return super.execute(identity, resourceId,arguments);
    }
  }

  @Override
  public List<Integer> getAvailableResourceIds(ObjectModel model) {
     return supportedResources;
  }

  private synchronized void setRoomcontrolName(String value) {
    if (vRoomcontrolName != value) {
       vRoomcontrolName = value;
 gvRoomcontrolName.setText(vRoomcontrolName);
       fireResourceChange(RES_ROOMCONTROL_NAME);
    }
  }

  private synchronized void setBidState(String value) {
    if (vBidState != value) {
       vBidState = value;
 gvBidState.setText(vBidState);
       fireResourceChange(RES_BID_STATE);
    }
  }

  private synchronized void setRequestedEnergyAmount(long value) {
    if (vRequestedEnergyAmount != value) {
       vRequestedEnergyAmount = value;
 gvRequestedEnergyAmount.setText(Long.toString(vRequestedEnergyAmount));
       fireResourceChange(RES_REQUESTED_ENERGY_AMOUNT);
    }
  }

  private synchronized void setRequestedPricePerEnergyUnit(long value) {
    if (vRequestedPricePerEnergyUnit != value) {
       vRequestedPricePerEnergyUnit = value;
 gvRequestedPricePerEnergyUnit.setText(Long.toString(vRequestedPricePerEnergyUnit));
       fireResourceChange(RES_REQUESTED_PRICE_PER_ENERGY_UNIT);
    }
  }

}
